/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    tracks: Track;
    leaves: Leaf;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    tracks: TracksSelect<false> | TracksSelect<true>;
    leaves: LeavesSelect<false> | LeavesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * People who can author and publish ZoomOut content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  displayName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * One book, one Track. A Track cannot be published without a non-endorsement disclaimer and at least one purchase link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracks".
 */
export interface Track {
  id: number;
  bookTitle: string;
  author: string;
  /**
   * For self-published titles, use "Independently published".
   */
  publisher?: string | null;
  /**
   * URL of the book cover image.
   */
  coverUrl?: string | null;
  description?: string | null;
  /**
   * Non-endorsement disclaimer, shown on the Track. Required to publish — this supports the fair-use position and is not optional copy.
   */
  disclaimer?: string | null;
  /**
   * Where a reader can buy the book. At least one complete link is required to publish: ZoomOut is positioned as a complement to the book, not a substitute for it.
   */
  purchaseLinks?:
    | {
        retailer: string;
        url: string;
        isAffiliate?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How many Leaves this Track is intended to have. Target is 15–30; ~20 is the Phase 1 planning figure.
   */
  leafCount?: number | null;
  /**
   * Mock content. Defaults to ON so nothing reaches production by accident — untick only for real, fact-checked content.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One learning unit: Summary → Scenario → Payoff → Sticky Notes → Takeaway. All five must be filled in before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaves".
 */
export interface Leaf {
  id: number;
  /**
   * The Track this Leaf belongs to.
   */
  trackId: number | Track;
  /**
   * Position within the Track, starting at 0.
   */
  orderIndex: number;
  title: string;
  /**
   * Short, fast-to-read framing of the concept.
   */
  summary?: {
    body?: string | null;
    /**
     * Reserved for Phase 2 voiceover. Unused in Phase 1.
     */
    audio?: {
      url?: string | null;
      durationSeconds?: number | null;
    };
  };
  /**
   * A relatable situation with three answer options. Exactly one must be correct — that is the gate that unlocks the Payoff slide.
   */
  scenario?: {
    prompt?: string | null;
    /**
     * Exactly three. Tick exactly one as correct.
     */
    options?:
      | {
          text?: string | null;
          /**
           * Never sent to the app with the options — the server decides correctness.
           */
          isCorrect?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Reserved for Phase 2 voiceover. Unused in Phase 1.
     */
    audio?: {
      url?: string | null;
      durationSeconds?: number | null;
    };
  };
  /**
   * The deeper explanation, unlocked only after a correct answer.
   */
  payoff?: {
    body?: string | null;
    /**
     * Reserved for Phase 2 voiceover. Unused in Phase 1.
     */
    audio?: {
      url?: string | null;
      durationSeconds?: number | null;
    };
  };
  /**
   * Key points, shown as notes on a board.
   */
  stickyNotes?: {
    /**
     * Between 2 and 6 notes.
     */
    notes?:
      | {
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Reserved for Phase 2 voiceover. Unused in Phase 1.
     */
    audio?: {
      url?: string | null;
      durationSeconds?: number | null;
    };
  };
  /**
   * The one thing to remember, plus an optional deep-cut fact.
   */
  takeaway?: {
    body?: string | null;
    /**
     * Optional deep-cut fact. Cannot be saved without a Source Reference on the "takeaway" slide — an unsourced claim attributed to a real author is the highest-severity risk in the product.
     */
    dinnerTableKnowledge?: string | null;
    /**
     * Reserved for Phase 2 voiceover. Unused in Phase 1.
     */
    audio?: {
      url?: string | null;
      durationSeconds?: number | null;
    };
  };
  /**
   * Where each factual claim comes from. Required for Dinner Table Knowledge, and the audit trail the fair-use position rests on.
   */
  sourceReferences?:
    | {
        slideKey: 'summary' | 'scenario' | 'payoff' | 'stickyNotes' | 'takeaway';
        chapter?: string | null;
        page?: string | null;
        quote?: string | null;
        /**
         * What in the book supports this. Required.
         */
        note: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Mock content. Defaults to ON so nothing reaches production by accident — untick only for real, fact-checked content.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'tracks';
        value: number | Track;
      } | null)
    | ({
        relationTo: 'leaves';
        value: number | Leaf;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracks_select".
 */
export interface TracksSelect<T extends boolean = true> {
  bookTitle?: T;
  author?: T;
  publisher?: T;
  coverUrl?: T;
  description?: T;
  disclaimer?: T;
  purchaseLinks?:
    | T
    | {
        retailer?: T;
        url?: T;
        isAffiliate?: T;
        id?: T;
      };
  leafCount?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaves_select".
 */
export interface LeavesSelect<T extends boolean = true> {
  trackId?: T;
  orderIndex?: T;
  title?: T;
  summary?:
    | T
    | {
        body?: T;
        audio?:
          | T
          | {
              url?: T;
              durationSeconds?: T;
            };
      };
  scenario?:
    | T
    | {
        prompt?: T;
        options?:
          | T
          | {
              text?: T;
              isCorrect?: T;
              id?: T;
            };
        audio?:
          | T
          | {
              url?: T;
              durationSeconds?: T;
            };
      };
  payoff?:
    | T
    | {
        body?: T;
        audio?:
          | T
          | {
              url?: T;
              durationSeconds?: T;
            };
      };
  stickyNotes?:
    | T
    | {
        notes?:
          | T
          | {
              note?: T;
              id?: T;
            };
        audio?:
          | T
          | {
              url?: T;
              durationSeconds?: T;
            };
      };
  takeaway?:
    | T
    | {
        body?: T;
        dinnerTableKnowledge?: T;
        audio?:
          | T
          | {
              url?: T;
              durationSeconds?: T;
            };
      };
  sourceReferences?:
    | T
    | {
        slideKey?: T;
        chapter?: T;
        page?: T;
        quote?: T;
        note?: T;
        id?: T;
      };
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
